import { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  overwrite: true,
  schema: "https://us-east-1.cdn.hygraph.com/content/cl8z8boma0tpz01ul4h162cir/master",
  documents: "src/queries/**/*.{gql,graphql}",
  emitLegacyCommonJSImports: false,
  config: {
    scalars: {
      RichTextAST: "@graphcms/rich-text-types#RichTextContent",
      DateTime: "string",
      Date: "string",
      Hex: "string",
      Css: "string",
      Long: "string",
      Json: "string",
    },
    Test: "ConfigQuery.configuration",
  },
  generates: {
    "src/types/schema.ts": {
      plugins: [
        "typescript",
        "typescript-operations",
        "fragment-matcher",
        "typed-document-node",
        "typescript-resolvers",
        {
          add: {
            content: `/* eslint-disable */

// WARNING
//
// This file is automatically generated by GraphQL Code Generator
// If you modify it, your changes will be overwritten. So don't modify it.
// Or do, whatever. I'm not your mother.
//
// END OF WARNING
`,
          },
        },
      ],
    },
  },
};

export default config;
