query blogPostsByTags($tag: String!, $stage: Stage = PUBLISHED) {
  blogPosts(stage: $stage, orderBy: updatedAt_DESC, where: { blogPostTags_some: { tag: $tag } }) {
    description
    id
    publishedAt
    slug
    title
    overrideDate
    blogPostTags {
      tag
    }
    authors {
      name
      photo {
        fileName
        height
        mimeType
        size
        url
        width
      }
      title
    }
    body {
      raw
      references {
        ... on Admonition {
          id
          body {
            raw
          }
          title
          type
        }
        ... on Asset {
          id
          mimeType
          size
          url
          width
          height
          fileName
        }
        ... on ContentButton {
          id
          colorScheme
          link
          showIcon
          text
          variant
        }
      }
    }
  }
}
