query blogPostsByTags($tag: String!, $stage: Stage = PUBLISHED) {
  blogPosts(stage: $stage, orderBy: updatedAt_DESC, where: { contentTags_some: { tag: $tag } }) {
    description
    id
    publishedAt
    slug
    title
    overrideDate
    contentTags {
      tag
    }
    authors {
      name
      photo {
        fileName
        height
        mimeType
        size
        url
        width
      }
      title
    }
    body {
      raw
      references {
        ... on Admonition {
          id
          body {
            raw
          }
          title
          type
        }
        ... on Asset {
          id
          mimeType
          size
          url
          width
          height
          fileName
        }
        ... on ContentButton {
          id
          colorScheme
          link
          showIcon
          text
          variant
        }
        ... on Document {
          id
          name
          file {
            fileName
            mimeType
            size
            url
          }
        }
        ... on DocumentGroup {
          id
          name
          documents(where: { file: { mimeType: "application/pdf" } }) {
            id
            name
            file {
              fileName
              mimeType
              size
              url
            }
          }
        }
      }
    }
  }
}
