query blogPost($slug: String, $stage: Stage = PUBLISHED) {
  blogPost(where: { slug: $slug }, stage: $stage) {
    publishedAt
    description
    slug
    title
    overrideDate
    blogPostTags {
      tag
    }
    authors {
      name
      title
      photo {
        mimeType
        size
        url
        width
        height
        fileName
      }
    }
    body {
      raw
      references {
        ... on Admonition {
          id
          body {
            raw
          }
          title
          type
        }
        ... on Asset {
          id
          fileName
          height
          mimeType
          size
          url
          width
        }
        ... on ContentButton {
          id
          colorScheme
          link
          showIcon
          text
          variant
        }
      }
    }
  }
}
