query config($title: String) {
  values: configuration(where: { title: $title }) {
    description
    organizationName
    slogan
    title
    titleOverrides
    statusUrl
    socialLinks(first: 10) {
      id
      name
      href
    }
    errorMessage {
      id
      name
      level
      title
      body {
        raw
      }
    }
    callToAction {
      shown
      title
    }
    testimonials(first: 10) {
      body {
        raw
      }
      image {
        fileName
        handle
        height
        mimeType
        size
        url(
          transformation: {
            image: { resize: { height: 113, fit: clip } }
            document: { output: { format: webp } }
          }
        )
        width
      }
      subtitle
      title
    }
    createdAt
    subscribe {
      id
      button {
        id
        action
        alert {
          body {
            raw
          }
          level
          name
          title
        }
        text
        variant
      }
      fields {
        ... on CheckboxField {
          __typename
          displayName
          formId
          label
          multiple
          options
          required
          fieldGroup
        }
        ... on SelectField {
          __typename
          displayName
          formId
          label
          multiple
          options
          required
          fieldGroup
        }
        ... on TextAreaField {
          __typename
          displayName
          formId
          label
          required
          fieldGroup
        }
        ... on TextInputField {
          __typename
          displayName
          formId
          label
          required
          fieldGroup
        }
      }
      colorScheme
    }
  }
}
