query docsPage($slug: String, $stage: Stage = PUBLISHED) {
  docsPage(where: { slug: $slug }, stage: $stage) {
    body {
      raw
      references {
        ... on Admonition {
          id
          body {
            raw
          }
          title
          type
        }
        ... on Asset {
          id
          mimeType
          size
          url
          width
          height
          fileName
        }
        ... on ContentButton {
          id
          colorScheme
          link
          showIcon
          text
          variant
        }
      }
    }
    description
    slug
    showUpdatedDate
    title
    docsGroup {
      slug
    }
    updatedAt
  }
}
