query docsGroups($stage: Stage = PUBLISHED) {
  docsGroups(first: 20, stage: $stage) {
    callToAction {
      body {
        raw
      }
      enable
      icon {
        mimeType
        height
        size
        url
        width
        fileName
      }
      iconColor
    }
    docsPages {
      body {
        raw
        references {
          ... on Admonition {
            id
            body {
              raw
            }
            title
            type
          }
          ... on Asset {
            id
            mimeType
            size
            url
            width
            height
            fileName
          }
          ... on ContentButton {
            id
            colorScheme
            link
            showIcon
            text
            variant
          }
        }
      }
      updatedAt
      title
      slug
      showUpdatedDate
      description
      docsGroup {
        slug
      }
    }
    slug
    subtitle
    title
    summary {
      raw
      references {
        ... on Admonition {
          id
          body {
            raw
          }
          title
          type
        }
        ... on Asset {
          id
          mimeType
          size
          url
          width
          height
          fileName
        }
        ... on ContentButton {
          id
          colorScheme
          link
          showIcon
          text
          variant
        }
      }
    }
  }
}
