query employees($config: String) {
  configuration(where: { title: $config }) {
    employees(first: 50) {
      bio {
        raw
      }
      name
      photo {
        fileName
        height
        mimeType
        size
        url
        width
      }
      title
    }
  }
}
