query employees($config: String, $stage: Stage = PUBLISHED) {
  configuration(where: { title: $config }, stage: $stage) {
    employees(first: 50) {
      bio {
        raw
      }
      name
      location
      photo {
        fileName
        height
        mimeType
        size
        url(
          transformation: {
            image: { resize: { fit: crop, height: 256, width: 256 } }
            document: { output: { format: webp } }
          }
        )
        width
      }
      title
    }
  }
}
