query homePage($name: String, $stage: Stage = PUBLISHED) {
  homePage(stage: $stage, where: { name: $name }) {
    blocks(first: 10) {
      body {
        raw
      }
      button {
        link
        text
        variant
      }
      image {
        fileName
        height
        mimeType
        size
        url
        width
        handle
      }
      subtitle
      title
    }
    mainVideo {
      fileName
      handle
      height
      mimeType
      size
      url
      width
    }
  }
}
