query officeLocations {
  officeLocations(stage: PUBLISHED) {
    closeTime
    name
    openTime
    photo {
      fileName
      height
      width
      url(
        transformation: {
          image: { resize: { width: 128, height: 128, fit: max } }
          document: { output: { format: webp } }
        }
      )
      mimeType
      size
    }
    location {
      latitude
      longitude
    }
    address {
      address1
      address2
      address3
      city
      state
      zipCode
    }
  }
}
