query page($slug: String, $stage: Stage = PUBLISHED) {
    page(where: { slug: $slug }, stage: $stage) {
        body {
            raw
        }
        callout {
            body {
                raw
            }
            button {
                link
                text
                variant
            }
            subtitle
            title
            form {
                name
                colorScheme
                button {
                    __typename
                    id
                    action
                    alert {
                        level
                        name
                        title
                        body {
                            raw
                        }
                    }
                    text
                    variant
                }
                fields(first: 50) {
                    ... on FormGroup {
                        __typename
                        name
                        groupId
                    }
                    ... on CheckboxField {
                        __typename
                        displayName
                        formId
                        label
                        multiple
                        options
                        required
                        fieldGroup
                    }
                    ... on SelectField {
                        __typename
                        displayName
                        formId
                        label
                        multiple
                        creatable
                        options
                        required
                        fieldGroup
                    }
                    ... on AddressSearchField {
                        __typename
                        displayName
                        formId
                        label
                        required
                        locationType
                        fieldGroup
                    }
                    ... on RemoteSelectField {
                        __typename
                        displayName
                        formId
                        label
                        multiple
                        dataPath
                        required
                        fieldGroup
                    }
                    ... on TextAreaField {
                        __typename
                        displayName
                        formId
                        label
                        required
                        fieldGroup
                    }
                    ... on TextInputField {
                        __typename
                        displayName
                        formId
                        label
                        required
                        validationType
                        fieldGroup
                    }
                    ... on DateField {
                        __typename
                        displayName
                        formId
                        label
                        required
                        fieldGroup
                        range
                        allowFuture
                        allowPast
                        fieldGroup
                    }
                    ... on CurrencyField {
                        __typename
                        displayName
                        formId
                        label
                        required
                        fieldGroup
                        unitSymbol
                    }
                }
            }
        }
        slug
        title
        subtitle
        footerTitle
        contents {
            body {
                raw
            }
            button {
                text
                link
                variant
            }
            features {
                body {
                    raw
                }
                button {
                    link
                    text
                    variant
                }
                icon {
                    fileName
                    height
                    mimeType
                    size
                    url
                    width
                }
                iconColor
                title
            }
            form {
                name
                colorScheme
                button {
                    __typename
                    id
                    action
                    alert {
                        level
                        name
                        title
                        body {
                            raw
                        }
                    }
                    text
                    variant
                }
                fields(first: 50) {
                    ... on FormGroup {
                        __typename
                        name
                        groupId
                    }
                    ... on CheckboxField {
                        __typename
                        displayName
                        formId
                        label
                        multiple
                        options
                        required
                        fieldGroup
                    }
                    ... on SelectField {
                        __typename
                        displayName
                        formId
                        label
                        creatable
                        multiple
                        options
                        required
                        fieldGroup
                    }
                    ... on RemoteSelectField {
                        __typename
                        displayName
                        formId
                        label
                        multiple
                        dataPath
                        required
                        fieldGroup
                    }
                    ... on TextAreaField {
                        __typename
                        displayName
                        formId
                        label
                        required
                        fieldGroup
                    }
                    ... on TextInputField {
                        __typename
                        displayName
                        formId
                        label
                        required
                        validationType
                        fieldGroup
                    }
                    ... on AddressSearchField {
                        __typename
                        displayName
                        formId
                        locationType
                        label
                        required
                        fieldGroup
                    }
                    ... on DateField {
                        __typename
                        displayName
                        formId
                        label
                        required
                        fieldGroup
                        range
                        allowFuture
                        allowPast
                        fieldGroup
                    }
                    ... on CurrencyField {
                        __typename
                        displayName
                        formId
                        label
                        required
                        fieldGroup
                        unitSymbol
                    }
                }
            }
            image {
                fileName
                mimeType
                size
                url
                width
                height
            }
            slug
            showUpdatedDate
            subtitle
            title
            updatedAt
            vendorLogo {
                __typename
                darkColor {
                    hex
                }
                lightColor {
                    hex
                }
                logo {
                    size
                    mimeType
                    width
                    url
                    height
                }
                postText
                pretext
                name
            }
        }
    }
}
