name: Quality
on: [push, pull_request]

jobs:
    quality:
        name: Quality
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Node Setup
              uses: actions/setup-node@v4
              with:
                  node-version: latest

            - name: PNPM Setup
              uses: pnpm/action-setup@v4
              with:
                  version: latest
                  run_install: true

            - name: Formatting
              run: pnpm run format

            - name: Lint
              run: pnpm run lint

            - name: Typing
              run: pnpm run typecheck
